export enum Rarity {
  UNIQUE = 'UNIQUE',
  MYTHIQUE = 'MYTHIQUE',
  CELESTE = 'CELESTE',
  LEGENDAIRE = 'LEGENDAIRE',
  EPIC = 'EPIC',
  SUPER_RARE = 'SUPER RARE',
  RARE = 'RARE',
  PEU_COMMUN = 'PEU COMMUN',
  COMMUN = 'COMMUN',
}
