export enum RoleEnum {
  PLAYER = 'PLAYER',
  HELPER = 'HELPER',
  MODERATOR = 'MODERATOR',
  SUPER_MODERATOR = 'SUPER MODERATOR',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER-ADMIN',
  PROJECT_OWNER = 'PROJECT OWNER',
}
